// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.smartOffice;

public interface containsPrintJobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsPrintJob)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();

  /**
   * <code>string staples = 3;</code>
   */
  java.lang.String getStaples();
  /**
   * <code>string staples = 3;</code>
   */
  com.google.protobuf.ByteString
      getStaplesBytes();
}
