// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplies.proto

package grpc.smartOffice;

public interface containsOrderConfirmationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsOrderConfirmation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
