// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplies.proto

package grpc.smartOffice;

public interface containsOfficeSuppliesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsOfficeSupplies)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string supply_id = 1;</code>
   */
  java.lang.String getSupplyId();
  /**
   * <code>string supply_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSupplyIdBytes();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
