// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplies.proto

package grpc.smartOffice;

public interface orderTotalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orderTotal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string total = 1;</code>
   */
  java.lang.String getTotal();
  /**
   * <code>string total = 1;</code>
   */
  com.google.protobuf.ByteString
      getTotalBytes();
}
