// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.smartOffice;

public interface printerStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printerStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
