// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.smartOffice;

public interface printerStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printerStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string activity = 1;</code>
   */
  java.lang.String getActivity();
  /**
   * <code>string activity = 1;</code>
   */
  com.google.protobuf.ByteString
      getActivityBytes();

  /**
   * <code>int32 inkLevels = 2;</code>
   */
  int getInkLevels();

  /**
   * <code>string paper = 3;</code>
   */
  java.lang.String getPaper();
  /**
   * <code>string paper = 3;</code>
   */
  com.google.protobuf.ByteString
      getPaperBytes();

  /**
   * <code>int32 queue = 4;</code>
   */
  int getQueue();

  /**
   * <code>int32 staplesRemaining = 5;</code>
   */
  int getStaplesRemaining();
}
