// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.smartOffice;

public final class PrinterProto {
  private PrinterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsPrintJob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsPrintJob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_confirmationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_confirmationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printerStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printerStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprinter.proto\"F\n\020containsPrintJob\022\017\n\007c" +
      "ontent\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\022\017\n\007staple" +
      "s\030\003 \001(\t\"+\n\023confirmationMessage\022\024\n\014confir" +
      "mation\030\001 \001(\t\"\"\n\017containsRequest\022\017\n\007reque" +
      "st\030\001 \001(\t\"l\n\rprinterStatus\022\020\n\010activity\030\001 " +
      "\001(\t\022\021\n\tinkLevels\030\002 \001(\005\022\r\n\005paper\030\003 \001(\t\022\r\n" +
      "\005queue\030\004 \001(\005\022\030\n\020staplesRemaining\030\005 \001(\0052w" +
      "\n\007printer\0222\n\005print\022\021.containsPrintJob\032\024." +
      "confirmationMessage\"\000\0228\n\020getPrinterUpdat" +
      "e\022\020.containsRequest\032\016.printerStatus\"\0000\001B" +
      "\"\n\020grpc.smartOfficeB\014PrinterProtoP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsPrintJob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsPrintJob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsPrintJob_descriptor,
        new java.lang.String[] { "Content", "Quantity", "Staples", });
    internal_static_confirmationMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_confirmationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_confirmationMessage_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_containsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_containsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_printerStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_printerStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printerStatus_descriptor,
        new java.lang.String[] { "Activity", "InkLevels", "Paper", "Queue", "StaplesRemaining", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
