// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.smartOffice;

public final class PrinterProto {
  private PrinterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsPrintJob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsPrintJob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_confirmationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_confirmationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printerStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printerStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprinter.proto\"F\n\020containsPrintJob\022\017\n\007c" +
      "ontent\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\022\017\n\007staple" +
      "s\030\003 \001(\t\"+\n\023confirmationMessage\022\024\n\014confir" +
      "mation\030\001 \001(\t\"\"\n\017containsRequest\022\017\n\007reque" +
      "st\030\001 \001(\t\"(\n\rprinterStatus\022\027\n\017responseMes" +
      "sage\030\001 \001(\t2w\n\007printer\0222\n\005print\022\021.contain" +
      "sPrintJob\032\024.confirmationMessage\"\000\0228\n\020get" +
      "PrinterUpdate\022\020.containsRequest\032\016.printe" +
      "rStatus\"\0000\001B\"\n\020grpc.smartOfficeB\014Printer" +
      "ProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsPrintJob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsPrintJob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsPrintJob_descriptor,
        new java.lang.String[] { "Content", "Quantity", "Staples", });
    internal_static_confirmationMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_confirmationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_confirmationMessage_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_containsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_containsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_printerStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_printerStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printerStatus_descriptor,
        new java.lang.String[] { "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
