// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.smartOffice;

/**
 * Protobuf type {@code printerStatus}
 */
public  final class printerStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:printerStatus)
    printerStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use printerStatus.newBuilder() to construct.
  private printerStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private printerStatus() {
    activity_ = "";
    inkLevels_ = 0;
    paper_ = "";
    queue_ = 0;
    staplesRemaining_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private printerStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            activity_ = s;
            break;
          }
          case 16: {

            inkLevels_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            paper_ = s;
            break;
          }
          case 32: {

            queue_ = input.readInt32();
            break;
          }
          case 40: {

            staplesRemaining_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.smartOffice.PrinterProto.internal_static_printerStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.smartOffice.PrinterProto.internal_static_printerStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.smartOffice.printerStatus.class, grpc.smartOffice.printerStatus.Builder.class);
  }

  public static final int ACTIVITY_FIELD_NUMBER = 1;
  private volatile java.lang.Object activity_;
  /**
   * <code>string activity = 1;</code>
   */
  public java.lang.String getActivity() {
    java.lang.Object ref = activity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      activity_ = s;
      return s;
    }
  }
  /**
   * <code>string activity = 1;</code>
   */
  public com.google.protobuf.ByteString
      getActivityBytes() {
    java.lang.Object ref = activity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      activity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INKLEVELS_FIELD_NUMBER = 2;
  private int inkLevels_;
  /**
   * <code>int32 inkLevels = 2;</code>
   */
  public int getInkLevels() {
    return inkLevels_;
  }

  public static final int PAPER_FIELD_NUMBER = 3;
  private volatile java.lang.Object paper_;
  /**
   * <code>string paper = 3;</code>
   */
  public java.lang.String getPaper() {
    java.lang.Object ref = paper_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paper_ = s;
      return s;
    }
  }
  /**
   * <code>string paper = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPaperBytes() {
    java.lang.Object ref = paper_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paper_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUEUE_FIELD_NUMBER = 4;
  private int queue_;
  /**
   * <code>int32 queue = 4;</code>
   */
  public int getQueue() {
    return queue_;
  }

  public static final int STAPLESREMAINING_FIELD_NUMBER = 5;
  private int staplesRemaining_;
  /**
   * <code>int32 staplesRemaining = 5;</code>
   */
  public int getStaplesRemaining() {
    return staplesRemaining_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getActivityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, activity_);
    }
    if (inkLevels_ != 0) {
      output.writeInt32(2, inkLevels_);
    }
    if (!getPaperBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, paper_);
    }
    if (queue_ != 0) {
      output.writeInt32(4, queue_);
    }
    if (staplesRemaining_ != 0) {
      output.writeInt32(5, staplesRemaining_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getActivityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, activity_);
    }
    if (inkLevels_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, inkLevels_);
    }
    if (!getPaperBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, paper_);
    }
    if (queue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, queue_);
    }
    if (staplesRemaining_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, staplesRemaining_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.smartOffice.printerStatus)) {
      return super.equals(obj);
    }
    grpc.smartOffice.printerStatus other = (grpc.smartOffice.printerStatus) obj;

    boolean result = true;
    result = result && getActivity()
        .equals(other.getActivity());
    result = result && (getInkLevels()
        == other.getInkLevels());
    result = result && getPaper()
        .equals(other.getPaper());
    result = result && (getQueue()
        == other.getQueue());
    result = result && (getStaplesRemaining()
        == other.getStaplesRemaining());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTIVITY_FIELD_NUMBER;
    hash = (53 * hash) + getActivity().hashCode();
    hash = (37 * hash) + INKLEVELS_FIELD_NUMBER;
    hash = (53 * hash) + getInkLevels();
    hash = (37 * hash) + PAPER_FIELD_NUMBER;
    hash = (53 * hash) + getPaper().hashCode();
    hash = (37 * hash) + QUEUE_FIELD_NUMBER;
    hash = (53 * hash) + getQueue();
    hash = (37 * hash) + STAPLESREMAINING_FIELD_NUMBER;
    hash = (53 * hash) + getStaplesRemaining();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.smartOffice.printerStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartOffice.printerStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartOffice.printerStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartOffice.printerStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartOffice.printerStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartOffice.printerStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartOffice.printerStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smartOffice.printerStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smartOffice.printerStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.smartOffice.printerStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smartOffice.printerStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smartOffice.printerStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.smartOffice.printerStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code printerStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:printerStatus)
      grpc.smartOffice.printerStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.smartOffice.PrinterProto.internal_static_printerStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.smartOffice.PrinterProto.internal_static_printerStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.smartOffice.printerStatus.class, grpc.smartOffice.printerStatus.Builder.class);
    }

    // Construct using grpc.smartOffice.printerStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      activity_ = "";

      inkLevels_ = 0;

      paper_ = "";

      queue_ = 0;

      staplesRemaining_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.smartOffice.PrinterProto.internal_static_printerStatus_descriptor;
    }

    @java.lang.Override
    public grpc.smartOffice.printerStatus getDefaultInstanceForType() {
      return grpc.smartOffice.printerStatus.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.smartOffice.printerStatus build() {
      grpc.smartOffice.printerStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.smartOffice.printerStatus buildPartial() {
      grpc.smartOffice.printerStatus result = new grpc.smartOffice.printerStatus(this);
      result.activity_ = activity_;
      result.inkLevels_ = inkLevels_;
      result.paper_ = paper_;
      result.queue_ = queue_;
      result.staplesRemaining_ = staplesRemaining_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.smartOffice.printerStatus) {
        return mergeFrom((grpc.smartOffice.printerStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.smartOffice.printerStatus other) {
      if (other == grpc.smartOffice.printerStatus.getDefaultInstance()) return this;
      if (!other.getActivity().isEmpty()) {
        activity_ = other.activity_;
        onChanged();
      }
      if (other.getInkLevels() != 0) {
        setInkLevels(other.getInkLevels());
      }
      if (!other.getPaper().isEmpty()) {
        paper_ = other.paper_;
        onChanged();
      }
      if (other.getQueue() != 0) {
        setQueue(other.getQueue());
      }
      if (other.getStaplesRemaining() != 0) {
        setStaplesRemaining(other.getStaplesRemaining());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.smartOffice.printerStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.smartOffice.printerStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object activity_ = "";
    /**
     * <code>string activity = 1;</code>
     */
    public java.lang.String getActivity() {
      java.lang.Object ref = activity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        activity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string activity = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActivityBytes() {
      java.lang.Object ref = activity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string activity = 1;</code>
     */
    public Builder setActivity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      activity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string activity = 1;</code>
     */
    public Builder clearActivity() {
      
      activity_ = getDefaultInstance().getActivity();
      onChanged();
      return this;
    }
    /**
     * <code>string activity = 1;</code>
     */
    public Builder setActivityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      activity_ = value;
      onChanged();
      return this;
    }

    private int inkLevels_ ;
    /**
     * <code>int32 inkLevels = 2;</code>
     */
    public int getInkLevels() {
      return inkLevels_;
    }
    /**
     * <code>int32 inkLevels = 2;</code>
     */
    public Builder setInkLevels(int value) {
      
      inkLevels_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 inkLevels = 2;</code>
     */
    public Builder clearInkLevels() {
      
      inkLevels_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object paper_ = "";
    /**
     * <code>string paper = 3;</code>
     */
    public java.lang.String getPaper() {
      java.lang.Object ref = paper_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paper_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string paper = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPaperBytes() {
      java.lang.Object ref = paper_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paper_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string paper = 3;</code>
     */
    public Builder setPaper(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      paper_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string paper = 3;</code>
     */
    public Builder clearPaper() {
      
      paper_ = getDefaultInstance().getPaper();
      onChanged();
      return this;
    }
    /**
     * <code>string paper = 3;</code>
     */
    public Builder setPaperBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      paper_ = value;
      onChanged();
      return this;
    }

    private int queue_ ;
    /**
     * <code>int32 queue = 4;</code>
     */
    public int getQueue() {
      return queue_;
    }
    /**
     * <code>int32 queue = 4;</code>
     */
    public Builder setQueue(int value) {
      
      queue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 queue = 4;</code>
     */
    public Builder clearQueue() {
      
      queue_ = 0;
      onChanged();
      return this;
    }

    private int staplesRemaining_ ;
    /**
     * <code>int32 staplesRemaining = 5;</code>
     */
    public int getStaplesRemaining() {
      return staplesRemaining_;
    }
    /**
     * <code>int32 staplesRemaining = 5;</code>
     */
    public Builder setStaplesRemaining(int value) {
      
      staplesRemaining_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 staplesRemaining = 5;</code>
     */
    public Builder clearStaplesRemaining() {
      
      staplesRemaining_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:printerStatus)
  }

  // @@protoc_insertion_point(class_scope:printerStatus)
  private static final grpc.smartOffice.printerStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.smartOffice.printerStatus();
  }

  public static grpc.smartOffice.printerStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<printerStatus>
      PARSER = new com.google.protobuf.AbstractParser<printerStatus>() {
    @java.lang.Override
    public printerStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new printerStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<printerStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<printerStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.smartOffice.printerStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

