// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplies.proto

package grpc.smartOffice;

public final class SuppliesProto {
  private SuppliesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsOfficeSupplies_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsOfficeSupplies_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containsOrderConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containsOrderConfirmation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016supplies.proto\"=\n\026containsOfficeSuppli" +
      "es\022\021\n\tsupply_id\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\"" +
      "1\n\031containsOrderConfirmation\022\024\n\014confirma" +
      "tion\030\001 \001(\t2T\n\010supplies\022H\n\rorderSupplies\022" +
      "\027.containsOfficeSupplies\032\032.containsOrder" +
      "Confirmation\"\000(\001B#\n\020grpc.smartOfficeB\rSu" +
      "ppliesProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_containsOfficeSupplies_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containsOfficeSupplies_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsOfficeSupplies_descriptor,
        new java.lang.String[] { "SupplyId", "Quantity", });
    internal_static_containsOrderConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_containsOrderConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containsOrderConfirmation_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
